services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api

    container_name: sc_api

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui

    container_name: sc_ui

    ports:
      - "8501:8501"

    env_file:
      - .env

    volumes:
      - .:/app

    depends_on:
      - api