FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# install uv
RUN pip install uv

# copy project FIRST
COPY . .

# now requirements.txt exists
RUN uv pip install --system -r requirements.txt




# # RUN chmod +x /app/scripts/entrypoint.sh
# RUN sed -i 's/\r//' /app/scripts/entrypoint.sh && \
#     chmod +x /app/scripts/entrypoint.sh

EXPOSE 8000

CMD ["python", "scripts/start.py"]

# CMD ["/app/scripts/entrypoint.sh"]
# CMD ["uvicorn", "run:app", "--host", "0.0.0.0", "--port", "8000"]