# FROM python:3.11-slim

# ENV PYTHONDONTWRITEBYTECODE=1
# ENV PYTHONUNBUFFERED=1

# WORKDIR /app

# COPY requirements.txt .

# RUN pip install --no-cache-dir -r requirements.txt

# COPY . .

# EXPOSE 8501

# FROM python:3.11-slim

# ENV PYTHONDONTWRITEBYTECODE=1
# ENV PYTHONUNBUFFERED=1

# WORKDIR /app

# COPY requirements.txt .

# RUN pip install --no-cache-dir -r requirements.txt

# COPY . .

# EXPOSE 8501

# CMD ["streamlit", "run", "ui/test_ui.py", "--server.address=0.0.0.0", "--server.port=8501"]


FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# install uv
RUN pip install uv

# copy dependency files first (better caching)
COPY requirements.txt .

# install dependencies using uv
RUN uv pip install --system -r requirements.txt

# copy full project
COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "ui/test_ui.py", "--server.address=0.0.0.0", "--server.port=8501"]
